### ISSUE TITLE
Needs build instructions to get a binary

### ISSUE THREAD

**Issue by hzeller** [antmicro/TermSharp#2]
Just tried to build TermSharp, but since I don't know what is used in the mono-world, I tried `xbuild` and it does something, but in `bin/Debug/` there are only two dll's that show up. Can I build a binary ?

(background: wanted test if [timg](https://timg.sh) creates a nice output, with iterm2 and unicode blocks)

**Comment by pgielda** [comment]
Its a widget for Xwt so technically its a library (which in mono-world are .dlls), not a standalone program (which in mono-world are .exe files).
This library is used e.g. by Renode (so technically you could build Renode and test it this way but that is overcomplicated) -- but I do think its a good idea to have a "demo" app (that e.g. runs bash in a window), @PiotrZierhoffer what do you think?

**Comment by hzeller** [comment]
Yes, I think a testing program that starts a standalone terminal-emulator in a window would be good.

**Comment by PiotrZierhoffer** [comment]
Hi @hzeller , I added a trivial example of usage. You can go to the `Example` dir and run `xbuild` inside.

**Comment by hzeller** [comment]
cool!
I get a bunch of errors like
```
Xwt.GtkBackend/Gtk2Extensions.cs(153,67): error CS0246: The type or namespace name `Gtk' could not be found. Are you missing an assembly reference?
```

I suspect that I have a library missing ?

**Comment by pgielda** [comment]
I suspect you are missing gtk bindings (GtkSharp). Those tend to be tricky so I let @PiotrZierhoffer specify the details on how to get those. Probably depends on your distro, what are you using to build?

**Comment by PiotrZierhoffer** [comment]
That's correct, GtkSharp is a required dependency. The package is usually called `gtk-sharp2` (or `gtk-sharp-2` on Arch Linux).

**Comment by hzeller** [comment]
Thanks, this works!
