### ISSUE TITLE
Bright colors not supported

### ISSUE THREAD

**Issue by lcavalli** [antmicro/TermSharp#3]
ANSI escape codes, as reported in https://en.wikipedia.org/wiki/ANSI_escape_code, support as non-standard extension (but common in modern terminals) bright colors as seen also in this table from Wikipedia:

![image](https://user-images.githubusercontent.com/6123641/143613742-e8f59edd-5937-4317-bdfd-8261e1cdecdf.png)

Codes are in range 90-97 for foreground and 100-107 for background.

Being not supported, running an executable that use bright colors in renode produces a list of warnings and text is printed with default color:

```
16:22:28.2409 [WARNING] Unimplemented SGR code 92. (2)
16:22:28.2419 [WARNING] Unimplemented SGR code 93.
16:22:28.4942 [WARNING] Unimplemented SGR code 92.
16:22:28.4952 [WARNING] Unimplemented SGR code 93. (2)
16:22:28.7652 [WARNING] Unimplemented SGR code 92.
```

**Comment by mateusz-holenko** [comment]
Thanks @lcavalli for reporting this issue and preparing a PR. The support for bright colors is merged in: https://github.com/antmicro/TermSharp/commit/cdc16d77d466b42b2cb6a494ee6aa79263ccc2f5.
